### ISSUE TITLE
The latest installer DICOM.Sort-2.1.9-win32.msi seems not work well

### ISSUE THREAD

**Issue by davidak03** [suever/dicomSort#30]
Dear Suever,
I am a new user, thanks for your wonderful work!

My PC OS is Windows 10.
In short, when I do the "Sort Images" in Release 2.1.9, selecting the new folder, the tool stays at "Ready...", DICOM files are sorted, the directories are empty.

As comparison, I got the previous release 2.1.8 from my friend, the "Sort Images" works well. The DICOM files are sorted as the Properties selected.

So I guess there may be a bug, hope this could help a little.

Thanks!
David

**Comment by suever** [comment]
Sorry about this! I'll look into it for you and post here when I figure out what the issue is.

**Comment by suever** [comment]
Hmmm I'm not able to reproduce this on Windows 10. Do you receive any error messages?

Also, you mention that the tool's status stays at "Ready..." but then you say that the files are sorted. So does it just create the folders where the DICOMs would go, and just doesn't copy the files to the correct location?

To help me debug it, can you select the folder and then rather than hitting "Sort Images" open up the debug window from the Window menu and paste the output of `app.frame.config` here?

![image](https://user-images.githubusercontent.com/653357/34572479-7a5217ca-f13f-11e7-8893-6ad75f98a8af.png)

**Comment by davidak03** [comment]
Thanks for reply.
Sorry, I should say "DICOM files are NOT sorted, the directories are empty."
And I did not receive error message. The window looks like this:
![image](https://user-images.githubusercontent.com/26403632/34597064-683d3a98-f21f-11e7-81ca-d26e03d5b93d.png)

However, I may find the reason ---- it could be caused by the path name, which contains Chinese characters.

As you requested, I past the debug window content below：
![image](https://user-images.githubusercontent.com/26403632/34597393-46f65be2-f221-11e7-98a4-0a18f68beb80.png)

**Comment by davidak03** [comment]
While I select  a source directory without Chinese character in the path name, DICOMsort works.

**Comment by davidak03** [comment]
I saw the target folders are created, but are empty.
