### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by David852-droid** [suever/dicomsort#52]
Hello, could I ask you:
- how could I get original data about pacient, if they were anonymized? Is it possible?
- when I sort the files, could I change it back, to get original names and sorting or is it non-reversable change?
 I'm not programmer and I couldn't find answers on dicomsort website, so I apologize, if my questions are simple. Thank you.

**Comment by suever** [comment]
Hey @David852-droid, the anonymization is irreversible by design so you will not be able to recover any fields that were removed from the images during sorting.

If you want to keep the original files alongside the sorted files, you can check the "Keep Original Files" option in the Miscellaneous tab of the Preferences dialog:

![image](https://user-images.githubusercontent.com/653357/71668068-84a2cd80-2d35-11ea-9734-217e1c291982.png)
